# Site settings
title: DevOps Engineering Notes
description: >-
  Comprehensive DevOps learning platform with practical guides, 
  real-world examples, and production-ready configurations for 
  modern software delivery practices.

baseurl: "/Devops_Notes"
url: "https://rohandeb2.github.io"

# Author information
author: 
  name: "Rohan Deb"
  email: "rohandeb2@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
twitter:
  username: rohandeb2
  card: summary_large_image

social:
  name: DevOps Engineering Notes
  links:
    - https://github.com/rohandeb2/Devops_Notes
    - https://github.com/rohandeb2

# Google Analytics (optional - replace with your ID)
# google_analytics: G-XXXXXXXXXX

# Navigation menu
header_pages:
  - linux/readme.md
  - "Git and Github/readme.md"
  - Jenkins/readme.md

# Exclude files from processing
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.gemspec"
  - README.md

# Include files
include:
  - _pages

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rohan Deb"
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "page"

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Syntax highlighting
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
